#!/usr/bin/env python3
"""One-time seed of tools/catalog.json from the existing back catalog."""
import json, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent

# series, slug, date, date_display, title, headline, summary, meta, source
R = [
("field-report","2026-08","2026-08-01","Aug 1","August 2026 Field Report",
 "Harvest season is here",
 "Almond harvest starts early and the pistachio off-year crop runs short. Silage corn chopping, cotton into cutout, pomegranate split — and why post-harvest soil sampling matters now.",
 "Crop status · Fertilizer · Market brief",
 "26 Field Report Newsletter/B Mello August 2026 Field Report.html"),
("field-report","2026-07","2026-07-01","Jul 1","July 2026 Field Report",
 "Almond hull split underway",
 "Cotton at peak bloom, wheat harvest wrapping up, table grape harvest active. Spotlight: compost and soil/water testing while commercial nitrogen stays expensive.",
 "Crop status · Fertilizer · Market brief",
 "26 Field Report Newsletter/B Mello July 2026 Field Report - UPDATED.html"),
("field-report","2026-05","2026-05-01","May 1","May 2026 Field Report",
 "Full gear across the Valley",
 "The hull split window nears, pistachios are in post-bloom nut fill, corn and cotton planting are active. Spotlight: JABB SBb 2.5™ and Nitryx™.",
 "Crop status · Fertilizer · Market brief",
 "26 Field Report Newsletter/B Mello May 2026 Newsletter.html"),
("field-report","2026-04","2026-04-01","Apr 1","April 2026 Field Report",
 "One of the highest-leverage months in the Valley",
 "Pistachio bloom is active, wheat prices are firming, and almond hull split is on an August target. Spotlight: Premium 97™ and Premium 95™ HA.",
 "Crop status · Fertilizer · Market brief",
 "26 Field Report Newsletter/B Mello April 2026 Newsletter.html"),

("ag-crime","2026-08","2026-08-13","Aug 13","August 2026 Ag Crime Report",
 "Harvest is peak theft season",
 "A serial copper thief arrested in Ventura County, a 500-vase metal ring broken by the Fresno ag task force, plus county briefs statewide.",
 "County briefs · Trends · Statewide hotspot map",
 "26 Rural Crime Newsletter/B Mello August 2026 Ag Crime Report.html"),
("ag-crime","2026-08-hotspot-map","2026-08-12","Aug 12","California Ag Crime Hotspot Map — August 2026",
 "California Ag Crime Hotspot Map",
 "The interactive county watch list that ships with the August report — click a county and see what is being hit.",
 "Interactive · Companion to the August report",
 "26 Rural Crime Newsletter/ca-ag-crime-hotspot-map-interactive.html"),

("economic-update","2026-08","2026-08-15","Aug 15","August 2026 Economic Update",
 "Book fall soil sampling now",
 "An El Niño winter may shorten the post-harvest window. Class I skim drops $2.73, CVP allocation raised, corn $4.48, wheat $6.52.",
 "Milk & dairy · Futures · Fuel · Weather · Water",
 "26 Economic Update Newsletter/B_Mello_Economic_Update_August_2026.html"),
("economic-update","2026-07","2026-07-15","Jul 15","July 2026 Economic Update",
 "Milk, fuel, futures and the 2026 pistachio crop",
 "Corn around $4.38, wheat $6.32, Class III at $16.15, California diesel about $6.07 — plus the water situation and Central Valley weather.",
 "Milk & dairy · Futures · Fuel · Water · Weather",
 "26 Economic Update Newsletter/B Mello Economic Update July 2026 - UPDATED.html"),
("economic-update","2026-05","2026-05-15","May 15","May 2026 Economic Update",
 "Class III under pressure as the flush peaks",
 "Cheese and butter mixed, corn around $4.35, wheat $5.52, and California diesel at $7.89.",
 "Milk & dairy · Futures · Fuel · Water · Weather",
 "26 Economic Update Newsletter/Economic Update May 2026.html"),
("economic-update","2026-04","2026-04-15","Apr 15","April 2026 Economic Update",
 "Record cow numbers cap Class III",
 "Strong production keeps futures capped near $16.00, and California diesel hits an all-time high at $7.73.",
 "Milk & dairy · Futures · Fuel · Water · Weather",
 "26 Economic Update Newsletter/Economic Update April_2026 Newsletter v3.html"),

("energy","2026-08-24","2026-08-24","Aug 24","Weekly Energy Update — August 24, 2026",
 "The gap closed, exactly as we said it would",
 "Diesel refining margins set an all-time record above $100 a barrel and California diesel jumped 20¢ in a week to $7.142.",
 "Week 35 · Week in review Aug 17–23",
 "26 Weekly Energy Update/B Mello Weekly Energy Update - August 24 2026.html"),
("energy","2026-08-17","2026-08-17","Aug 17","Weekly Energy Update — August 17, 2026",
 "The dip is over",
 "Drones hit two tankers in the Strait of Hormuz and diesel futures rose almost 10% in five days — but the pump still priced last week's low.",
 "Week 34 · Week in review Aug 10–16",
 "26 Weekly Energy Update/B Mello Weekly Energy Update - August 17 2026.html"),
("energy","2026-08-10","2026-08-10","Aug 10","Weekly Energy Update — August 10, 2026",
 "The break we said would need a Hormuz deal showed up",
 "Both crude benchmarks fell more than 7% and California pump prices finally turned lower.",
 "Week 33 · Week in review Aug 3–9",
 "26 Weekly Energy Update/B Mello Weekly Energy Update - August 10 2026.html"),
("energy","2026-08-03","2026-08-03","Aug 3","Weekly Energy Update — August 3, 2026",
 "The relief did not come",
 "Brent closed July at $90.12 — its strongest month since March — and California diesel pushed to $6.91. We look higher again this week.",
 "Week 32 · Week in review Jul 27–Aug 2",
 "26 Weekly Energy Update/B Mello Weekly Energy Update - August 3 2026.html"),
("energy","2026-07-27","2026-07-27","Jul 27","Weekly Energy Update — July 27, 2026",
 "Another leg up on Hormuz risk and $90 crude",
 "Diesel and gasoline both moved higher again last week. Here is what it means for your fuel budget.",
 "Week 31 · Week in review Jul 20–26",
 "26 Weekly Energy Update/B Mello Weekly Energy Update - July 27 2026.html"),

("fishing","2026-08-19","2026-08-19","Aug 19–26","Weekly Fishing Report — August 19–26, 2026",
 "Rockfish and lingcod still wide open",
 "Thirteen days left on the salmon season, only 2 of 10 trips at limits, and the fall striper run is pouring into the Delta.",
 "Issue 26-34",
 "26 Fishing Report/B Mello Weekly Fishing Report - Aug 19-26 2026.html"),
("fishing","2026-08-12","2026-08-12","Aug 12–19","Weekly Fishing Report — August 12–19, 2026",
 "New moon Thursday, last minus tides until Aug 25",
 "The salmon fleet cooled off hard — 5 of 29 trips at limits — Fort Bragg is now closed, and Pine Flat is down 10.7 feet in six weeks.",
 "Issue 26-33",
 "26 Fishing Report/B Mello Weekly Fishing Report - Aug 12-19 2026.html"),
("fishing","2026-08-07","2026-08-07","Aug 7–14","Weekly Fishing Report — August 7–14, 2026",
 "Salmon limits off the Gate, fish to 32 lb",
 "The best minus tides of the month land Aug 10–12 right alongside the new moon. Fort Bragg salmon closes Aug 10.",
 "Issue 26-32",
 "26 Fishing Report/B Mello Weekly Fishing Report - Aug 7-14 2026.html"),

("special","2026-07-sulfur-price-alert","2026-07-20","Jul 20","Special Report: Sulfur Price Alert",
 "Sulfur Price Alert",
 "Global conflict is tightening sulfur supply — about $890/MT Qatar FOB, up roughly 300% year over year, with Russia's export ban running through Dec 31. If you can pre-pay and take delivery, do it now.",
 "Market alert · Time-sensitive",
 "26 Special Reports/B Mello Special Report - Sulfur Price Alert July 2026 - UPDATED.html"),

("holiday","2026-07-04","2026-07-04","Jul 4","Happy 4th of July",
 "Happy Independence Day",
 "Land of the free, because of the brave — from the B. Mello Ag Services family.",
 "Holiday greeting",
 "Holiday Newsletter/B Mello 4th of July EMAIL.html"),
("holiday","2026-06-21","2026-06-21","Jun 21","Happy Father's Day",
 "Happy Father's Day",
 "Thank you for planting the seeds of hard work, values, and a strong future.",
 "Holiday greeting",
 "Holiday Newsletter/B Mello Fathers Day Email HTML.html"),
("holiday","2026-05-25","2026-05-25","May 25","Memorial Day 2026",
 "Honoring our heroes this Memorial Day",
 "B Mello Ag Services honors the brave men and women who gave all for our freedom.",
 "Holiday greeting",
 "Holiday Newsletter/B Mello Memorial Day 2026.html"),
("holiday","2026-04-05","2026-04-05","Apr 5","Happy Easter",
 "Happy Easter",
 "May you be surrounded by the love of family and the sound of children's laughter.",
 "Holiday greeting",
 "Holiday Newsletter/B Mello Easter Newsletter 2026.html"),
]

items = []
for series, slug, date, disp, title, headline, summary, meta, source in R:
    items.append({
        "id": f"{series}/{slug}",
        "series": series,
        "slug": slug,
        "date": date,
        "date_display": disp,
        "title": title,
        "headline": headline,
        "summary": summary,
        "meta": meta,
        "source": source,
        "path": f"reports/{series}/{slug}.html",
    })

items.sort(key=lambda i: (i["date"], i["series"]), reverse=True)
(ROOT / "tools" / "catalog.json").write_text(
    json.dumps(items, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
print(f"catalog.json seeded with {len(items)} issues")
